#include "option_must_have_at_least_short_or_long_name.hpp"
#include "invalid_format_for_short_option_name.hpp"
#include "invalid_format_for_long_option_name.hpp"
#include "option_is_required_but_not_added.hpp"
#include "option_expects_argument.hpp"
#include "option_already_added_as.hpp"
#include "unrecognized_option.hpp"
